sudo: false
language: cpp
matrix:
  include:
      #docker
      - os: linux
        services: docker
        script:
          - docker build --build-arg BRANCH_NAME=$TRAVIS_BRANCH --build-arg REPO_SLUG=$TRAVIS_REPO_SLUG -f scripts/docker/debian/Dockerfile-stretch .
      - os: linux
        services: docker
        script:
          - docker build --build-arg BRANCH_NAME=$TRAVIS_BRANCH --build-arg REPO_SLUG=$TRAVIS_REPO_SLUG -f scripts/docker/debian/Dockerfile-jessie .
      #cross compile windows
      - os: linux
        services: docker
        script:
          - docker build --build-arg BRANCH_NAME=$TRAVIS_BRANCH --build-arg REPO_SLUG=$TRAVIS_REPO_SLUG -f scripts/docker/windows-crosscompile/Dockerfile-wheezy .
      - os: linux
        services: docker
        script:
          - docker build --build-arg BRANCH_NAME=$TRAVIS_BRANCH --build-arg REPO_SLUG=$TRAVIS_REPO_SLUG -f scripts/docker/windows-crosscompile/Dockerfile-xenial .
      #ubuntu
      - os: linux
        sudo: required
        before_install:
          - ./scripts/dependencies-ubuntu.sh
        install: true
        script:
          - ./scripts/install-ubuntu.sh
      #cross compile windows
      - os: linux
        sudo: required
        before_install:
          - sudo apt-get update && sudo apt-get install -yqq libtool-bin 
          - ./scripts//windows-crosscompile/dependencies.sh
        install: true
        script:
          - ./scripts/windows-crosscompile/compile-peercoin.sh
      #osx     
      - os: osx
        osx_image: xcode9.2
        before_script:
          - ./scripts/dependencies-osx.sh 
        script:
          - ./scripts/install-osx.sh

