sudo: false
language: cpp
matrix:
  include:
      #linux
      - os: linux
        services: docker
        script:
          - docker build --build-arg BRANCH_NAME=$TRAVIS_BRANCH --build-arg REPO_SLUG=$TRAVIS_REPO_SLUG -f scripts/docker/debian/Dockerfile-stretch .
      - os: linux
        services: docker
        script:
          - docker build --build-arg BRANCH_NAME=$TRAVIS_BRANCH --build-arg REPO_SLUG=$TRAVIS_REPO_SLUG -f scripts/docker/debian/Dockerfile-jessie .
      - os: linux
        sudo: required
        before_install:
          - ./scripts/dependencies-ubuntu.sh
        install: true
        script:
          - ./scripts/install-ubuntu.sh
      #cross compile windows
      - os: linux
        services: docker
        script:
          - travis_wait 60 docker build --build-arg BRANCH_NAME=$TRAVIS_BRANCH --build-arg REPO_SLUG=$TRAVIS_REPO_SLUG -f scripts/docker/windows-crosscompile/Dockerfile-wheezy .
      - os: linux
        services: docker
        script:
          - travis_wait 60 docker build --build-arg BRANCH_NAME=$TRAVIS_BRANCH --build-arg REPO_SLUG=$TRAVIS_REPO_SLUG -f scripts/docker/windows-crosscompile/Dockerfile-xenial .
      - os: linux
        services: docker
        script:
          - travis_wait 60 docker build --build-arg BRANCH_NAME=$TRAVIS_BRANCH --build-arg REPO_SLUG=$TRAVIS_REPO_SLUG -f scripts/docker/windows-crosscompile/Dockerfile-trusty .
      - os: linux
        sudo: required
        before_install:
          - travis_wait 60 cd scripts/windows-crosscompile && ./dependencies.sh
        install: true
        script:
          - travis_wait 60 ./scripts/windows-crosscompile/compile-peercoin.sh
      #osx     
      - os: osx
        osx_image: xcode9.2
        before_script:
          - ./scripts/dependencies-osx.sh 
        script:
          - ./scripts/install-osx.sh

