sudo: false
language: cpp
matrix:
  include:
      #linux
      - os: linux
        services: docker
        env:
          - V=Dockerfile-stretch
        script:
          - ./archive.sh
          - docker build -f scripts/docker/debian/Dockerfile-stretch .
      - os: linux
        services: docker
        env:
          - V=Dockerfile-jessie
        script:
          - ./archive.sh
          - docker build -f scripts/docker/debian/Dockerfile-jessie .
      - os: linux
        sudo: required
  ccache: true
        env:
          - V=ubuntu
# 32-bit + dash
    - HOST=i686-pc-linux-gnu PACKAGES="g++-multilib python3-zmq" DEP_OPTS="NO_QT=1" RUN_TESTS=true GOAL="install" BITCOIN_CONFIG="--enable-zmq --enable-glibc-back-compat --enable-reduce-exports LDFLAGS=-static-libstdc++" USE_SHELL="/bin/dash"
# Qt4 & system libs
    - HOST=x86_64-unknown-linux-gnu PACKAGES="python3-zmq qt4-dev-tools libssl-dev libevent-dev bsdmainutils libboost-system-dev libboost-filesystem-dev libboost-chrono-dev libboost-program-options-dev libboost-test-dev libboost-thread-dev libdb5.1++-dev libminiupnpc-dev libzmq3-dev libprotobuf-dev protobuf-compiler libqrencode-dev xvfb" NO_DEPENDS=1 NEED_XVFB=1 RUN_TESTS=true GOAL="install" BITCOIN_CONFIG="--enable-zmq --with-incompatible-bdb --enable-glibc-back-compat --enable-reduce-exports --with-gui=qt4 CPPFLAGS=-DDEBUG_LOCKORDER"
        before_install:
          - ./scripts/travis-uninstall-packages.sh
          - ./scripts/dependencies-ubuntu.sh
        install: true
    - if [ "$CHECK_DOC" = 1 ]; then git fetch --unshallow; fi
        script:
          - ./scripts/install-ubuntu.sh
      - os: linux
        sudo: required
        env:
          - V=ubuntu-debuild
        before_install:
          - ./scripts/travis-uninstall-packages.sh
          - ./scripts/dependencies-ubuntu.sh
        install: true
        script:
          - ./scripts/debuild.sh
      #cross compile windows
      #- os: linux
      #  services: docker
      #  env:
      #    - V=windows-Dockerfile-wheezy
      #  script:
      #    - ./archive.sh
      #    - travis_wait 60 docker build -f scripts/docker/windows-crosscompile/Dockerfile-wheezy .
      #- os: linux
      #  services: docker
      #  env:
      #    - V=windows-Dockerfile-xenial
      #  script:
      #    - ./archive.sh
      #    - travis_wait 60 docker build -f scripts/docker/windows-crosscompile/Dockerfile-xenial .
      #- os: linux
      #  services: docker
      #  env:
      #    - V=windows-Dockerfile-trusty
      #  script:
      #    - ./archive.sh
      #    - travis_wait 60 docker build -f scripts/docker/windows-crosscompile/Dockerfile-trusty .
      #- os: linux
      #  sudo: required
      #  env:
      #    - V=windows-ubuntu
      #  before_install:
      #    - cd $TRAVIS_BUILD_DIR/scripts/windows-crosscompile
      #    - pwd && ls -al
      #    - travis_wait 60 ./dependencies.sh
      #    - cd $TRAVIS_BUILD_DIR
      #  install: true
      #  script:
      #    - travis_wait 60 ./scripts/windows-crosscompile/compile-peercoin.sh
      #osx     
      #- os: osx
      #  osx_image: xcode9.2
      #  before_script:
      #    - ./scripts/dependencies-osx.sh
      #  script:
      #    - ./scripts/install-osx.sh

