sudo: false
language: cpp
matrix:
  include:
      - os: linux
        sudo: required
        before_install:
          - ./scripts/dependencies-ubuntu.sh
        install: true
        sudo: required
        script:
          - ./scripts/install-ubuntu.sh
      - os: osx
        before_script:
          - ./scripts/dependencies-osx.sh 
        script:
          - ./scripts/install-osx.sh
