sudo: false
language: cpp
matrix:
  include:
      - os: linux
        services: docker
        script:
          - docker build -f scripts/docker/debian/Dockerfile-stretch .
      - os: linux
        services: docker
        script:
          - docker build -f scripts/docker/debian/Dockerfile-jessie .
      - os: linux
        sudo: required
        before_install:
          - ./scripts/dependencies-ubuntu.sh
        install: true
        sudo: required
        script:
          - ./scripts/install-ubuntu.sh
      - os: osx
        osx_image: xcode9.2
        before_script:
          - ./scripts/dependencies-osx.sh 
        script:
          - ./scripts/install-osx.sh
